export const ROLES = {

    PMO_ADMIN: "PMO ADMIN",

    EXECUTIVE: "EXECUTIVE",

    PROJECT_SPONSOR: "PROJECT_SPONSOR",

    PROJECT_MANAGER: "PROJECT_MANAGER",

    TEAM_MEMBER: "TEAM_MEMBER",

    REVIEWER: "REVIEWER",

    DOCUMENT_CONTROLLER: "DOCUMENT_CONTROLLER",

    RISK_MANAGER: "RISK_MANAGER",

    QA: "QA",

    CLIENT: "CLIENT",

    INTERN: "INTERN"

};