export const initialTasks = [
  {
    id: 1,
    title: 'Setup Database Schema',
    category: 'Engineering',
    type: 'Feature',
    description: 'Design and deploy PostgreSQL schema with proper indexing, relationships, and migration scripts.',
    priority: 'High',
    status: 'Completed',
    assignee: 'John Doe',
    dueDate: '2026-07-20',
    kanbanStatus: 'Completed',
    checklist: [{ id: 101, text: 'Define tables', done: true }, { id: 102, text: 'Migrate DB', done: true }],
    attachments: ['schema_v1.png'],
    role: 'Lead Developer',
    workload: '10 hrs/wk',
    milestone: 'Sprint 1 Launch',
    completionDate: '2026-07-19',
    delayReason: null,
    progress: 100
  },
  {
    id: 2,
    title: 'Implement Auth API',
    category: 'Engineering',
    type: 'Feature',
    description: 'Build secure JWT authentication endpoints, password hashing, and middleware protection.',
    priority: 'High',
    status: 'In Progress',
    assignee: 'Jane Smith',
    dueDate: '2026-07-28',
    kanbanStatus: 'In Progress',
    checklist: [{ id: 103, text: 'JWT Service', done: true }, { id: 104, text: 'Middleware', done: false }],
    attachments: [],
    role: 'Backend Dev',
    workload: '15 hrs/wk',
    milestone: 'Beta Release',
    completionDate: null,
    delayReason: null,
    progress: 50
  },
  {
    id: 3,
    title: 'Design Resource Dashboard',
    category: 'Design',
    type: 'UI/UX',
    description: 'Create interactive Figma wireframes and high-fidelity prototypes for resource allocations.',
    priority: 'Medium',
    status: 'Pending',
    assignee: 'Alex Johnson',
    dueDate: '2026-08-05',
    kanbanStatus: 'To Do',
    checklist: [{ id: 105, text: 'UX Mockups', done: false }, { id: 106, text: 'User Feedback', done: false }],
    attachments: ['spec_doc.pdf'],
    role: 'UI/UX Designer',
    workload: '8 hrs/wk',
    milestone: 'UI Freeze',
    completionDate: null,
    delayReason: null,
    progress: 0
  },
  {
    id: 4,
    title: 'Security Audit & Vulnerability Scan',
    category: 'DevOps',
    type: 'Bug / Security',
    description: 'Review code for security vulnerabilities, dependency exploits, and penetration test compliance.',
    priority: 'High',
    status: 'Pending',
    assignee: 'Alex Johnson',
    dueDate: '2026-07-15',
    kanbanStatus: 'Blocked',
    checklist: [{ id: 107, text: 'Run Snyk Scan', done: true }, { id: 108, text: 'Patch dependencies', done: false }],
    attachments: [],
    role: 'Security Specialist',
    workload: '12 hrs/wk',
    milestone: 'Compliance Audit',
    completionDate: null,
    delayReason: 'Waiting for third-party security license approval',
    progress: 25
  },
  {
    id: 5,
    title: 'Stripe Payment Gateway Integration',
    category: 'Engineering',
    type: 'Feature',
    description: 'Integrate Stripe SDK for processing subscriptions, webhooks, and invoice generation.',
    priority: 'High',
    status: 'Pending',
    assignee: 'Jane Smith',
    dueDate: '2026-07-18',
    kanbanStatus: 'Blocked',
    checklist: [{ id: 109, text: 'API Keys Setup', done: true }, { id: 110, text: 'Webhook listener', done: false }],
    attachments: ['stripe_docs.pdf'],
    role: 'Backend Dev',
    workload: '20 hrs/wk',
    milestone: 'Beta Release',
    completionDate: null,
    delayReason: 'Pending sandbox credentials from finance team',
    progress: 10
  }
];

export const teamMembers = ['John Doe', 'Jane Smith', 'Alex Johnson', 'Unassigned'];

export const initialActivities = [
  { id: 1, text: 'Task "Setup Database Schema" updated.', timestamp: '10 mins ago' },
  { id: 2, text: 'New task created under Engineering', timestamp: '1 hour ago' },
  { id: 3, text: 'Stripe Integration marked as Blocked', timestamp: '3 hours ago' }
];